plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

author:
  name: Tommy Schmidt
  email: "darkatra@gmail.com"
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/DarkAtra" }
